---
title: "Learning blog"
subtitle: "A space to record the things I learn"
---

# 2026.02.06 Friday

Things I learned this week:

-   When it comes to reproducibility, don't forget to use renv and take snapshots with each upload of a new package.

-   Consumer price indices are an indicator of how prices of goods change. It's a relative scale, meaning you compare the value of interest with another value to understand how much prices increased with respect to that value.

-   Domestic gasoline price changes are driven largely by global oil prices. Brent oil prices are a good way to understand global oil prices. Domestic policy has only a small role to play on gas prices, affecting prices by only a few cents (large for the consumer but small compared to the effects of global oil prices).

I'm also learning a lot more about git as I'm trying to upgrade my skills with git to production-level. Right now I'm learning about personal access tokens vs. SSH keys.

# 2026.01.15 Thursday

(09:00 am) Spent some time learning about file naming systems. These are super important if you want your work to be reproducible or utilized. I have been very lucky to be a part of organizations that valued innovation in every aspect of the job. That even included file naming systems that scaled beyond our team, several levels wider into our ecosystem.

But there were limits to this scalability. Once the system was introduced beyond our ecosystem (e.g. another department, expert discipline or even another company), it took a tremendous amount of work to get teams aligned on the file naming system. I imagine this will be a challenge with any file naming system, but perhaps it's possible to scale it another few levels to save ourselves some time or to increase the intuitiveness to make it easier to decode.

A cool tool I discovered in R today is the "[targets](https://books.ropensci.org/targets/)" package. Allegedly, it allows you to create and follow lineages of iterations and transformations of data. I use the word "allegedly" because I have not tested it yet. But I'm about to right now. Here goes... (This is also why today's blog will have time stamped components to track my progress on figuring out this package).

(10:20 am) I was able to run one of the examples provided in the targets package user manual. It is impressive. Basically, targets allows you to specify what you are trying to track. It will then track any changes made to these targets and provide an illustration or a list of objects that need to be updated. It also provides a diagram of the lineage of these tracked objects. I think it's a very handy tool.

# 2026.01.14 Wednesday

Over and over again, I find that the biggest barrier to learning new things is not what I don't know, but what I do know. The closer I get to mastering something (and I don't have to get that close), the more it impedes my learning of new things. For example, I've known about parquets in R for a long time because I needed them a long time ago. But I never took the time to learn how to use them. Why? Because I already had ways of dealing with large datasets, clunky as they may be. While it's true that it would have taken more time to learn how to use parquets than implementing my clunky methods, the payoff long term would have been much higher. I guess it's important to remind ourselves to take the time and to take the risk (make sure you do a risk analysis first, obviously), to abandon what we know, temporarily and even permanently, to learn new and better ways of doing things.
