---
title: "Grid search accuracy results for random forest hyperparameters fit on Cleveland dataset"
output: 
  html_document:
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = "center", fig.height = 3, fig.width = 5)
library(easypackages)
libraries(
  c(
    "ggplot2", 
    "tidyverse", 
    "tidyr", 
    "ggpubr", 
    "janitor", 
    "gghalves", 
    "knitr", 
    "kableExtra", 
    "flextable", 
    "tidymodels", 
    "randomForest"
  )
)

```

```{r, include = FALSE}

output_df_final = read.csv("ROutput-RF tuning.csv")

output_df_final = 
  output_df_final %>%
  mutate(
    ntree_labels = 
      factor(
        ntree_labels,
        levels = 
          unique(ntree_labels)
      )
  )


```

The figure illustrates accuracies for differing values of the major hyperparameters (through grid search) of the random forest method: number of trees and number of variables to sample.

```{r, eval = TRUE, include = TRUE, echo = FALSE, fig.width = 16, fig.height = 7}

ggplot(
  output_df_final[sample(seq(1, dim(output_df_final)[1]), size = 10000), ], 
  aes(
    x = mtry, 
    y = accuracy, 
    # color = ntree, 
    group = mtry
  )
  
) + 
  # geom_boxplot(width = 0.1, outlier.shape = NA) +
  # geom_violin(width = 0.25, aes(group = mtry)) +
  geom_jitter(width = 1, alpha = 0.01, size = 15, shape = 21, fill = "grey", color = "grey") +
  geom_smooth(method = "loess", se = FALSE, aes(group = ntree)) +
  scale_x_continuous(
    breaks = seq(0, 10)
  ) + 
  # scale_y_continuous(
  #   limits = c(0.65, 0.1),
  #   breaks = seq(0.65, 1, 0.02)
  # ) +
  labs(
    x = "mtry", 
    y = "Accuracy", 
    title = "Accuracy vs. number of candidate predictors sampled at each split (mtry)"
  ) +
  facet_wrap(~ntree_labels, nrow = 2) + 
  theme(
      text = element_text(face = "bold", size = 20), 
      plot.title = element_text(hjust = 0.5), 
      plot.caption = element_text(hjust = 1),
      axis.text.x = element_text(size = 8, angle = 45, hjust = 1), 
      panel.background = element_rect(fill = NA, color = "black"), 
      panel.border = element_rect(fill = NA, color = "black"), 
      strip.background = element_rect(fill = NA, color = NA), 
      strip.text = element_text(size = 12)
    )
```
